name: learn-github-actions
run-name: print echo
on: [push]
jobs:
  print-echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "test"
  sleep-then-echo:
    runs-on: ubuntu-latest
    steps: 
      - run: sleep 1; echo "test";
  deploy-dev: 
    needs: ["print-echo", "sleep-then-echo"]
    environment: dev
    runs-on: ubuntu-latest
    steps: 
      - run: echo "dev deploy"
  deploy-qa: 
    needs: ["deploy-dev"]
    environment: qa
    runs-on: ubuntu-latest
    steps: 
      - run: echo "qa deploy"
  deploy-prod:
    needs: ["deploy-qa"]
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - run: "prod deploy"
