name: learn-github-actions
run-name: print echo
on: [push]
jobs:
  print-echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "test"
  sleep-long:
    runs-on: ubuntu-latest
    steps: 
      - run: sleep 10; echo "test";
      
